Repository prgrms-fe-devcourse/FEDC4_MUSSEUK_LETTER_Donggeun, pull requests merged in 2023-09, with the labels that each got.

#4 husky, lint-staged 패키지 설정
  .eslintrc.json
  .husky/pre-commit
  package-lock.json
  package.json
Labels: ⚙ Setting

#8 API 관련 세팅 #6
  .gitignore
  package-lock.json
  package.json
  src/apis/instance.ts
  src/apis/mutations/useLoginMutation.ts
  src/apis/queries/useAuthCheckQuery.ts
  src/apis/queryKeys.ts
  src/apis/types.ts
Labels: 📬 API

#22 Color 코드 상수화
  src/main.css
  src/main.tsx
Labels: 🎨 HTML&CSS

#23 chore: 이미지 에셋 추가
  src/assets/images/decoration_beer1.png
  src/assets/images/decoration_chicken1.png
  src/assets/images/decoration_coffee1.png
  src/assets/images/decoration_glasses1.png
  src/assets/images/decoration_hat1.png
  src/assets/images/decoration_medal1.png
  src/assets/images/decoration_soju1.png
  src/assets/images/decoration_uh1.png
  src/assets/images/musseuk_default.png
  src/assets/images/musseuk_heart.png
  src/assets/images/musseuk_hood.png
  src/assets/images/musseuk_labtop.png
  src/assets/images/musseuk_semicolon.png
Labels: ⚙ Setting

#26 chore: 패키지 설치 @hookform/resolvers zod
  package-lock.json
  package.json
Labels: ⚙ Setting

#24 회원가입 UI 작성
  src/pages/Signup/components/InputField.tsx
  src/pages/Signup/index.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#30 feat: chakra에 font, color 기본 설정 추가
  src/assets/fonts/netmarbleB.ttf
  src/assets/fonts/netmarbleL.ttf
  src/assets/fonts/netmarbleM.ttf
  src/main.css
  src/main.tsx
  src/theme/font.tsx
  src/theme/index.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#27 회원가입 페이지 로직 완성
  src/apis/mutations/useSignupMutation.ts
  src/pages/Signup/components/InputField.tsx
  src/pages/Signup/index.tsx
Labels: ✨ Feature

#28 feat: header UI 구현
  src/assets/images/logo.png
  src/components/header/components/Input/index.tsx
  src/components/header/index.tsx
  src/pages/Main/index.tsx
Labels: ✨ Feature

#33 refactor: 폰트 경로 수정, 회원가입 스타일 수정
  src/apis/mutations/useSignupMutation.ts
  src/main.tsx
  src/pages/Signup/components/InputField.tsx
  src/pages/Signup/index.tsx
  src/theme/font.tsx
Labels: 🔨 Refactor

#38 Primary 테마 속성 지정
  src/pages/Signup/index.tsx
  src/theme/index.tsx
Labels: ⚙ Setting

#35 feat: header 로그인 전/후 UI 변경 구현
  src/components/header/components/Button/index.tsx
  src/components/header/index.tsx
  src/pages/Main/index.tsx
Labels: ✨ Feature

#40 feat: 로그인 페이지 구현
  src/apis/mutations/useSigninMutation.ts
  src/pages/Signin/index.tsx
  src/pages/Signup/components/InputField.tsx
  src/pages/Signup/index.tsx
  src/pages/Signup/templates/LinkTemplate.tsx
  src/pages/Signup/templates/PageTemplate.tsx
  src/pages/Signup/templates/index.ts
Labels: ✨ Feature, 🔨 Refactor

#44 chore: API 기본 response 타입 지정
  src/apis/mutations/useSigninMutation.ts
  src/apis/mutations/useSignupMutation.ts
  src/apis/queries/useAuthCheckQuery.ts
  src/apis/types.ts
  src/types/index.ts
Labels: 📬 API

#51 feat: 로그인 정보 및 토큰 관리
  src/App.tsx
  src/apis/instance.ts
  src/apis/mutations/useSigninMutation.ts
  src/apis/mutations/useSignupMutation.ts
  src/apis/queries/useAuthCheckQuery.ts
  src/constants/storageKey.ts
  src/utils/storage.ts
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#52 feat: 로그아웃 구현 및 특정 페이지에서만 header 고정하도록 Router 수정
  src/App.tsx
  src/apis/mutations/useSignOutMutation.ts
  src/components/header/index.tsx
  src/pages/Main/index.tsx
  src/pages/Newpost/index.tsx
  src/pages/Post/index.tsx
  src/routes/layout/index.tsx
Labels: ✨ Feature

#57 rename: 폰트 경로 수정
  public/fonts/netmarbleB.ttf
  public/fonts/netmarbleL.ttf
  public/fonts/netmarbleM.ttf
  src/theme/font.tsx
Labels: ⚙ Setting, 🐞 Hotfix

#61 feat: 사용자 검색 api 구현
  src/apis/queries/useSearchUserQuery.ts
  src/apis/queryKeys.ts
  src/components/header/components/Input/index.tsx
  src/components/header/components/SearchBox/index.tsx
  src/components/header/index.tsx
Labels: ✨ Feature, 📬 API

#67 feat: mainpage, newpostpage UI 수정
  src/pages/Main/index.tsx
  src/pages/Newpost/index.tsx
  src/pages/Profile/components/ProfileBar.tsx
Labels: ✨ Feature

#73 feat: 검색 페이지 구현
  src/App.tsx
  src/apis/queries/useSearchUserQuery.ts
  src/components/header/components/Input/index.tsx
  src/components/header/components/SearchBox/index.tsx
  src/components/header/index.tsx
  src/pages/Search/components/UserCard/index.tsx
  src/pages/Search/index.tsx
  src/theme/index.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#77 feat: 회원가입, 로그인, 비밀번호 변경 페이지 접근 제한 기능
  src/pages/ChangePassword/index.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
Labels: ✨ Feature

#72 feat: 포스트 페이지 API 연결
  src/apis/queries/usePostDetailQuery.ts
  src/apis/queryKeys.ts
  src/apis/types.ts
  src/apis/utils/parseComment.ts
  src/apis/utils/parsePost.ts
  src/apis/utils/parseUser.ts
  src/pages/Post/index.tsx
  src/types/index.ts
Labels: ✨ Feature, 📬 API

#79 feat: 편지 1개 보기 모달 UI 구현
  src/assets/images/comment-header.png
  src/components/header/index.tsx
  src/pages/Post/components/CommentInfoModal/index.tsx
  src/pages/Post/components/CommentListModal/index.tsx
  src/pages/Post/index.tsx
Labels: ✨ Feature

#80 feat: 한눈에 보기 모달 구현
  src/components/Modal/index.tsx
  src/pages/Post/components/CommentListModal/AccordionItems/index.tsx
  src/pages/Post/components/CommentListModal/index.tsx
  src/pages/Post/index.tsx
Labels: ✨ Feature

#81 feat: 코멘트 표시 및 단일 코멘트 정보 모달 연결
  src/apis/utils/parseComment.ts
  src/assets/images/musseuk_laptop.png
  src/constants/imageNames.ts
  src/pages/Post/components/Comment.tsx
  src/pages/Post/components/CommentBoard.tsx
  src/pages/Post/components/CommentInfoModal/index.tsx
  src/pages/Post/components/CommentWriteModal/Decoration.tsx
  src/pages/Post/components/CommentWriteModal/DecorationList.tsx
  src/pages/Post/components/CommentWriteModal/index.tsx
  src/pages/Post/components/Musseuk.tsx
  src/pages/Post/constants/index.ts
  src/pages/Post/contexts/CommentInfoContext.ts
  src/pages/Post/contexts/CommentInfoProvider.tsx
  src/pages/Post/index.tsx
  src/types/index.ts
Labels: ✨ Feature

#84 hotfix: 이미지 import 경로 수정
  src/pages/Newpost/index.tsx
  src/pages/Profile/index.tsx
Labels: 🐞 Hotfix

#91 feat: comments 한눈에 보기 데이터 연결 + 헤더 알림 dropdown 추가
  src/App.tsx
  src/assets/images/icon-slack.png
  src/components/header/index.tsx
  src/pages/Post/components/CommentListModal/index.tsx
  src/pages/Post/index.tsx
  src/pages/Setting/Slack/index.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#90 슬랙 서버와 통신하는 인스턴스 생성
  src/apis/instance.ts
  src/apis/mutations/useGenerateSlackLinkMutation.ts
  src/constants/slack.ts
  src/types/index.ts
Labels: 📬 API

#93 코멘트 내용을 DM으로 발송하는 훅 작성
  src/apis/mutations/useGenerateSlackLinkMutation.ts
  src/apis/mutations/useSlackMessageMutation.ts
Labels: 📬 API

#95 refactor: 데이터 파싱 유틸 함수 리팩토링
  src/apis/utils/parseComment.ts
  src/apis/utils/parsePost.ts
  src/apis/utils/parseUser.ts
Labels: 🐞 Hotfix, 🔨 Refactor

#97 feat: NotFound 페이지 작성
  src/App.tsx
  src/assets/images/404_notfound.png
  src/pages/NotFound/index.tsx
Labels: ✨ Feature

#99 refactor: 회원가입 페이지의 PageTemplate 리팩토링
  src/App.tsx
  src/components/WhiteCard/PageTemplate.tsx
  src/components/WhiteCard/PageTemplateWithHeader.tsx
  src/components/WhiteCard/index.tsx
  src/components/header/index.tsx
  src/pages/ChangePassword/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
  src/pages/Signup/templates/PageTemplate.tsx
  src/pages/Signup/templates/index.ts
Labels: 🔨 Refactor

#102 feature: 슬랙 confirmation 페이지 ui
  src/App.tsx
  src/assets/images/musseuk_box.png
  src/pages/Setting/SlackConfirmation/index.tsx
Labels: ✨ Feature

#100 feat: 슬랙 알림 페이지 ui 구현 및 슬랙 api 연결
  src/assets/images/musseuk_slack.png
  src/pages/Setting/Slack/components/LinkField.tsx
  src/pages/Setting/Slack/index.tsx
Labels: ✨ Feature

#113 feat: 포스트 상세 페이지 리다이렉션 및 댓글 권한 설정
  src/apis/queries/usePostDetailQuery.ts
  src/apis/utils/parseComment.ts
  src/pages/Post/components/CommentBoard.tsx
  src/pages/Post/index.tsx
  src/types/index.ts
Labels: ✨ Feature, 🎨 HTML&CSS

#112 refactor: 사용자 인증 관련 query, mutation 훅 리팩토링
  src/apis/mutations/useSignOutMutation.ts
  src/apis/mutations/useSigninMutation.ts
  src/apis/mutations/useSignupMutation.ts
  src/apis/queries/useAuthCheckQuery.ts
Labels: 🐞 Hotfix, 🔨 Refactor

#116 refactor: useSlackTokenCheckQuery 리팩토링
  src/apis/queries/useSlackTokenCheckQuery.ts
  src/apis/queryClient.ts
  src/apis/queryKeys.ts
  src/main.tsx
Labels: 🔨 Refactor, 📬 API

#119 feature: 헤더 로고 반응형 수정
  src/assets/images/logo_mobile.png
  src/components/header/index.tsx
  src/theme/index.tsx
Labels: ✨ Feature

#122 hotfix: search 페이지- parsing한 데이터로 출력하도록 수정
  src/apis/queries/useSearchUserQuery.ts
  src/pages/Search/index.tsx
Labels: 🐞 Hotfix

#105 feat: 메인페이지, 머쓱이 생성페이지 기능 구현
  package-lock.json
  package.json
  src/apis/mutations/useNewPostMutation.ts
  src/apis/queries/useGetPostsInfoQuery.ts
  src/apis/queryKeys.ts
  src/apis/types.ts
  src/assets/images/table.png
  src/components/PostCard/index.tsx
  src/pages/Main/components/Description.tsx
  src/pages/Main/components/MusseukButton.tsx
  src/pages/Main/components/MusseukImage.tsx
  src/pages/Main/index.tsx
  src/pages/Newpost/components/MusseukItem.tsx
  src/pages/Newpost/index.tsx
  src/theme/index.tsx
Labels: ✨ Feature, 📬 API

#125 hotfix: profile 페이지 suspense 에러 임시해결 + 주석처리
  src/apis/utils/parseComment.ts
  src/apis/utils/parsePost.ts
  src/apis/utils/parseUser.ts
  src/components/header/index.tsx
  src/pages/Profile/index.tsx
Labels: 🐞 Hotfix

#130 feature: 비로그인 상태를 검사하는 useIsNotLoggedIn 훅 작성
  src/hooks/useIsNotLoggedIn.ts
  src/pages/ChangePassword/index.tsx
Labels: ✨ Feature, 🙋‍♂️ Question

#128 hotfix: husky가 특정 리눅스 환경에서 제대로 작동하지 않는 현상 해결
  .husky/pre-commit
  package-lock.json
  package.json
Labels: 🐞 Hotfix

#126 feat 포스트 상세 페이지 suspense 적용
  src/apis/queries/usePostDetailQuery.ts
  src/pages/Post/components/AnnouncementText.tsx
  src/pages/Post/components/CommentBoard.tsx
  src/pages/Post/components/DescriptionText.tsx
  src/pages/Post/components/Introduction.tsx
  src/pages/Post/components/Musseuk.tsx
  src/pages/Post/components/Skeletons/CommentBoardSkeleton.tsx
  src/pages/Post/components/Skeletons/IntroductionSkeleton.tsx
  src/pages/Post/index.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#135 feature: 로그인 페이지 리다이렉션 기능
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
Labels: ✨ Feature, 🔨 Refactor

#142 hotfix: 회원가입, 로그인, 비밀번호 변경 QA 반영
  src/apis/mutations/useSignupMutation.ts
  src/pages/ChangePassword/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/Signin/index.tsx
  src/pages/Signup/index.tsx
Labels: 🐞 Hotfix

#143 hotfix: 슬랙 인증 페이지 버그 수정 및 기능 추가
  src/apis/queries/useSlackTokenCheckQuery.ts
  src/pages/Setting/Slack/index.tsx
  src/pages/Setting/SlackConfirmation/index.tsx
Labels: 🐞 Hotfix, 📬 API

#146 hotfix: header 검색 버그 수정 및 스타일 수정
  src/apis/mutations/useProfileImageMutation.ts
  src/apis/queries/useSearchUserQuery.ts
  src/components/header/components/Menu/index.tsx
  src/components/header/index.tsx
Labels: 🐞 Hotfix

#156 feature: 세션 스토리지를 로컬 스토리지로 수정
  src/pages/Post/components/CommentBoard.tsx
Labels: ✨ Feature

#159 feat: 포스트 페이지 스타일 정리
  src/components/TextCount/index.tsx
  src/pages/Post/components/AnnouncementText.tsx
  src/pages/Post/components/Comment.tsx
  src/pages/Post/components/CommentBoard.tsx
  src/pages/Post/components/CommentInfoModal/index.tsx
  src/pages/Post/components/CommentWriteModal/Decoration.tsx
  src/pages/Post/components/CommentWriteModal/index.tsx
  src/pages/Post/components/Introduction.tsx
  src/pages/Post/components/Musseuk.tsx
  src/pages/Post/components/Skeletons/CommentBoardSkeleton.tsx
  src/pages/Post/constants/index.ts
  src/pages/Post/index.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#163 hotfix: issue, pr templates
  .github/ISSUE_TEMPLATE/✅-feature.md
  .github/ISSUE_TEMPLATE/🚨--hotfix.md
  .github/pull_request_template.md
Labels: 🐞 Hotfix

#164 hotfix: suspense 리팩토링 및 로그인 없이 편지링크에 접근시 리다이랙트 처리
  .pnp.cjs
  .yarn/cache/@esbuild-darwin-arm64-npm-0.18.20-00b3504077-8.zip
  .yarn/cache/@toss-async-boundary-npm-1.4.4-0bdc39e30a-a1ac3b2f94.zip
  .yarn/cache/@toss-error-boundary-npm-1.4.4-ac67b4182d-84843cd644.zip
  .yarn/cache/@toss-utils-npm-1.4.4-4da0dd0dcb-7013b5eb19.zip
  .yarn/cache/date-fns-npm-2.30.0-895c790e0f-f7be015232.zip
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  .yarn/cache/lodash-npm-4.17.21-6382451519-eb835a2e51.zip
  packages/web/package.json
  packages/web/src/pages/Post/index.tsx
  packages/web/src/pages/Setting/Slack/index.tsx
  packages/web/src/pages/Setting/SlackConfirmation/index.tsx
  yarn.lock
Labels: 🐞 Hotfix, 🔨 Refactor

#170 feat: 머쓱이 생성 페이지 tip ui 추가 구현
  packages/web/src/components/header/index.tsx
  packages/web/src/pages/Newpost/index.tsx
  packages/web/src/pages/Search/components/UserCard/index.tsx
  packages/web/src/pages/Search/index.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#174 hotfix: 인증하기 버튼 로딩 + 클릭 시 비활성화 추가
  packages/web/src/pages/Setting/Slack/index.tsx
Labels: 🐞 Hotfix

#167 feat: 포스트 페이지 에러 바운더리 추가
  packages/web/src/components/ErrorBoundaryCard/index.tsx
  packages/web/src/pages/Post/index.tsx
Labels: ✨ Feature

#168 feat: 회원가입, 로그인, 비밀번호 변경 페이지 버튼 로딩 처리
  packages/web/src/pages/ChangePassword/index.tsx
  packages/web/src/pages/Signin/index.tsx
  packages/web/src/pages/Signup/index.tsx
Labels: ✨ Feature

#179 hotfix: 무효한 로그인 토큰이면 스토리지에서 제거
  packages/web/src/apis/queries/useAuthCheckQuery.ts
Labels: 🐞 Hotfix

#176 feat: 코멘트 작성 모달 인풋 글자수 제한 및 버튼 로딩
  packages/web/src/pages/Post/components/CommentInfoModal/index.tsx
  packages/web/src/pages/Post/components/CommentListModal/AccordionItems/index.tsx
  packages/web/src/pages/Post/components/CommentWriteModal/index.tsx
  packages/web/src/pages/Post/components/Introduction.tsx
  packages/web/src/pages/Post/components/PostDeleteModal/index.tsx
Labels: ✨ Feature

#182 feat: 머쓱이 이미지 수정
  packages/web/src/assets/images/musseuk_heart.png
  packages/web/src/assets/images/musseuk_hood.png
  packages/web/src/assets/images/musseuk_laptop.png
  packages/web/src/assets/images/musseuk_semicolon.png
  packages/web/src/assets/images/table.png
  packages/web/src/pages/Main/components/Description.tsx
  packages/web/src/pages/Main/components/MusseukImage.tsx
  packages/web/src/pages/Main/index.tsx
  packages/web/src/pages/Newpost/index.tsx
Labels: 🎨 HTML&CSS

#184 chore: favicon 설정
  packages/web/index.html
  packages/web/public/favicon.png
  packages/web/public/vite.svg
Labels: ⚙ Setting

#188 feat: og 태그랑 링크 복사 버튼 추가
  packages/web/index.html
  packages/web/public/logo_og.png
  packages/web/src/pages/Post/components/ShareButton.tsx
  packages/web/src/pages/Post/index.tsx
Labels: ✨ Feature

#197 Docs: readme 파일 정리
  .pnp.cjs
  README.md
  packages/slack/README.md
  packages/web/README.md
  packages/web/package.json
  yarn.lock
Labels: ⚙ Setting, 📃 Docs
